language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "no test. Yes there will be tests"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag udagram-reverseproxy trustekpo/udagram-reverseproxy:v4b
  - docker tag udagram-api-user trustekpo/udagram-api-user:v4b
  - docker tag udagram-api-feed trustekpo/udagram-api-feed:v4b
  - docker tag udagram-frontend trustekpo/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trustekpo/udagram-reverseproxy:v4b
  - docker push trustekpo/udagram-api-user:v4b
  - docker push trustekpo/udagram-api-feed:v4b
  - docker push trustekpo/udagram-frontend:local

